---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: "jdk"


inputs:
  - name: git-repo
  - name: version

outputs:
  - name: artifact-dir

run:
  user: root
  path: sh
  args:
  - -exc
  - |
    gradle assemble -Pversion=$(cat version/number) -p git-repo
    cp git-repo/build/libs/*.war artifact-dir/
    ls artifact-dir
