---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "latest"

inputs:
  - name: git-repo
  - name: version
  - name: release-candidate

outputs:
  - name: final-dir

run:
  path: sh
  args:
  - -exc
  - |
    cp release-candidate/${base_name}*.jar final-dir/${base_name}-$(cat version/number).jar

params:
  base_name:
