---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: "jdk8"

inputs:
  - name: git-repo

run:
  user: root
  path: sh
  args:
  - -exc
  - |
    gradle -v
    gradle test -p git-repo
