---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "latest"


inputs:
  - name: git-repo

run:
  path: sh
  args:
  - -exc
  - |
    apk add --update curl
    git-repo/ci/scripts/verify-test.sh

params:
  CONCOURSE_DEMO_URL:
